apiVersion: v1
kind: Deployment
metadata:
  name: laravel
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/laravel
  uid: 02df2148-9858-4b7a-8ea9-d3d56d2a73ea
  resourceVersion: '86047'
  generation: 7
  creationTimestamp: '2020-11-17T07:55:59Z'
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '5'
    description: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 7
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-11-17T07:56:00Z'
      lastTransitionTime: '2020-11-17T07:56:00Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-11-17T09:41:33Z'
      lastTransitionTime: '2020-11-17T07:56:00Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "laravel-75cf5fbf68" has successfully progressed.
