---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/laravel
  uid: 02df2148-9858-4b7a-8ea9-d3d56d2a73ea
  resourceVersion: '86047'
  generation: 7
  creationTimestamp: '2020-11-17T07:55:59Z'
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '5'
    description: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravel
        version: v1
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
    spec:
      containers:
        - name: container-0
          image: 'swr.ap-southeast-1.myhuaweicloud.com/dev-hk/laravel-docker:10'
          env:
            - name: PAAS_APP_NAME
              value: laravel
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 09cfa301f38010582f03c00ac54c8b92
            - name: APP_KEY
              value: 'base64:cd8LkMsLlT+u3Gzp0kBHWXkysFcA3JltzVdpEE5BOHM='
            - name: APP_DEBUG
              value: 'true'
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
      dnsConfig:
        options:
          - name: timeout
            value: ''
          - name: ndots
            value: '5'
          - name: single-request-reopen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 7
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-11-17T07:56:00Z'
      lastTransitionTime: '2020-11-17T07:56:00Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-11-17T09:41:33Z'
      lastTransitionTime: '2020-11-17T07:56:00Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "laravel-75cf5fbf68" has successfully progressed.
