apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/laravel
  uid: 02df2148-9858-4b7a-8ea9-d3d56d2a73ea
  resourceVersion: '86047'
  generation: 7
  creationTimestamp: '2020-11-17T07:55:59Z'
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '5'
    description: ''